version: '3.1'

services:
  redis:
    image: redis
    restart: always
    container_name: 'redis'
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    restart: always
    container_name: 'django'
    command: gunicorn --bind :8000 --workers 3 config.wsgi:application
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
  celery:
    build: .
    container_name: 'celery'
    command: celery -A config worker -B
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}